export const CFG = {
  spatialScale: 2,
  width: 256,
  height: 160,
  dt: 0.1,
  snapshotEverySteps: 2,
  potentialEverySteps: 10,
  potentialDecay: 0.988,
  resourceMoveFraction: 0.58,
  baseEdgeCapacityPerSecond: 7.0,
  resourceCellCapacity: 1,
  resourceRearTargetUtilization: 0.06,
  resourceFrontTargetUtilization: 0.78,
  resourceTargetDensityExponent: 1.35,
  resourceDestinationDeficitBias: 0.75,
  resourceBelowTargetMoveFactor: 0.18,
  frontCommitmentSafety: 1.60,
  frontCommitmentMax: 1.0,
  frontCommitmentFloor: 0.025,
  frontOffensiveCommitmentShare: 0.82,
  frontUnopposedCommitment: 0.82,
  collapseCommitmentFactor: 0.28,
  commitmentEngagePerSecond: 0.85,
  commitmentReleasePerSecond: 0.22,
  collapseReleaseMultiplier: 3.0,
  frontBand: 0.34,
  frontBoundaryPadding: 1,
  massRadius: 4,
  defenceAdvantage: 1.36,
  baseProbe: 0.76,
  emptyFrontMass: 0.08,
  unopposedTinyMass: 0.025,
  unopposedUsefulMass: 0.35,
  unopposedAdvance: 2.5,
  maintenanceRate: 0.004,
  combatConsumptionRate: 0.010,
  instabilityGrow: 0.48,
  instabilityRecover: 0.16,
  collapseEnter: 1.0,
  collapseExit: 0.48,
  collapseAdvanceMultiplier: 3.0,
  controlSmooth: 0.17,
  controlRestore: 0.11,
  controlForce: 0.45,
  controlClamp: 0.999,
  cityIntegrationPerSecond: 1 / 70,
  cityCaptureThreshold: 0.42,
  noiseAmplitude: 0.02,
  initialCityResourceSeconds: 12,
  initialFrontResource: 1,
  warmupSeconds: 75,
} as const;

export const SPEEDS = [1, 2, 4, 8, 16] as const;

export type Side = 'blue' | 'red';
export type Speed = typeof SPEEDS[number];
